### PR TITLE
Update README.md - added tested device

### PR DESCRIPTION
**Pull request by SidColt**
added tested device in readme.md

### CODE REVIEW

**Comment by SidColt** [comment]
added tested device in readme.md

**Comment by drahdiwaberl** [comment]
do you think or found any hints this might be a TAC-12chsa/xa73i? looking lile "Vesker VSK-12000BTU" i think?

do you know of any resources showing how to wire this device?

**Comment by lNikazzzl** [comment]
> do you think or found any hints this might be a TAC-12chsa/xa73i? looking lile "Vesker VSK-12000BTU" i think?
> 
> do you know of any resources showing how to wire this device?

I don't know, only worked with my air conditioner. There is also a telegram group in Russian, where you can try to ask a question about your air conditioner in English. I don't think they will answer you, as there are not so many participants there yet. But send a photo of the board of your air conditioner anyway. Maybe someone will be able to advise you 

https://t.me/+Sx2zU05K_z8wZmNi

**Comment by drahdiwaberl** [comment]
well, the question was directed @SidColt, as he might be able to compare images with his device. 

anyways, i found this https://github.com/adaasch/AC-hack - which shows exactly the board(s) i have in the above mentioned device, as soon as i got it installed i'll swap the original wifi-board with an esp and give it a try with your yaml..

**Pull request merged**
